services:
  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: ./packages/infrastructure/Dockerfile.migrations
    env_file:
      - ./packages/infrastructure/.env 
    networks:
      - app_network
    restart: "no"  # Run once and exit

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./apps/worker/.env
    networks:
      - app_network
    depends_on:
      migrate:
        condition: service_completed_successfully
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./apps/api/.env
    networks:
      - app_network
    depends_on:
      migrate:
        condition: service_completed_successfully

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge