services:
  migrator:
    container_name: migrator
    build:
      context: .
      dockerfile: ./packages/infrastructure/Dockerfile.migrations
    networks:
      - app_network
    restart: "no"  # Run once and exit

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network
    depends_on:
      migrator:
        condition: service_completed_successfully
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      migrator:
        condition: service_completed_successfully

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge