services:
  db:
    container_name: database_dev_container
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: clean-architecture-boilerplate
      POSTGRES_USER: rustam
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    container_name: redis_dev_container
    image: redis:alpine
    restart: always
    networks:
      - app_network
  
  migrator:
    env_file:
      - ./packages/infrastructure/.env
    depends_on:
      - db
  
  worker:
    env_file:
      - ./apps/worker/.env
    depends_on:
      - db
      - redis
  
  api:
    env_file:
      - ./apps/api/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: